[package]
name = "rendering"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { version = "0.38.0" }
gpu-allocator = { workspace = true }
parking_lot = { version = "0.12.5" }
scope-guard = { workspace = true }
winit = { workspace = true }

[lints]
workspace = true
